label: 'Bibliothek benutzerdefinierter Blöcke'
display:
  default:
    display_title: Standard
    display_options:
      title: 'Bibliothek benutzerdefinierter Blöcke'
      fields:
        info:
          label: Blockbeschreibung
          separator: ', '
        type:
          label: Blocktyp
          separator: ', '
        changed:
          label: Aktualisiert
        operations:
          label: Aktionen
      pager:
        options:
          tags:
            next: 'Nächste Seite ›'
            previous: '‹ Vorherige Seite'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      filters:
        info:
          expose:
            label: Blockbeschreibung
        type:
          expose:
            label: Blocktyp
  page_1:
    display_title: Seite
    display_options:
      menu:
        title: 'Bibliothek benutzerdefinierter Blöcke'
